apiVersion: v2
# upstream version
appVersion: 0.0.32
name: local-path-provisioner
# giantswarm chart version
version: 0.0.1
description: Dynamically provisioning persistent local storage with Kubernetes
home: https://github.com/giantswarm/local-path-provisioner-app
icon: https://s.giantswarm.io/app-icons/giantswarm/1/light.svg
keywords:
  - storage
  - hostpath
annotations:
  io.giantswarm.application.audience: "giantswarm"
  io.giantswarm.application.managed: "true"
  io.giantswarm.application.team: "rocket"
maintainers:
  - name: Team Rocket
    email: team-rocket@giantswarm.io
sources:
  - https://github.com/rancher/local-path-provisioner
